Feature/isdb 265 step parent adoption
hmcts/fis-bulk-scan-api pull request #69
Opened 2022-06-20 12:34 UTC by rahulsanjava19

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-06-21 14:22 UTC, yogendraU requested changes

2022-06-21 15:59 UTC, rahulsanjava19 commented on src/functionalTest/resources/application.yaml
> +  api:
As discussed, we kept separate yaml for functional tests so needed to keep this property in order to bring up spring context

2022-06-27 10:15 UTC, yogendraU approved these changes

2022-06-28 16:27 UTC, hmcts-kodatala approved these changes
OK

2022-06-28 16:32 UTC, merged